galaxy_info:
  role_name: test_role_4
  author: astudio
  description: '-'
  company: '-'
  issue_tracker_url: '-'
  license: MIT
  min_ansible_version: '-'
  min_ansible_container_version: '-'
  github_branch: master
  galaxy_tags:
    - tag1
    - tag2
  platforms:
    - name: Debian
      versions:
        - all
dependencies: []
